# fly.toml app configuration file generated for blackjack-ts on 2023-12-21T20:47:46+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "blackjack-ts"
primary_region = "ams"

[build]

[http_service]
  internal_port = 3000
  force_https = true
  processes = ["app"]

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 1024
